<a href="https://colab.research.google.com/github/Lochan-01/ml/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [32]:
df= pd.read_csv('/content/Salary Data.csv')
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object
 2   Education Level      373 non-null    object
 3   Job Title            373 non-null    object
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [34]:
#to check the missing value
df.isnull().sum()
print(df.isnull().sum())

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [35]:
df.duplicated().sum()
print(df.duplicated().sum())

50

In [36]:
df.drop_duplicates(inplace=True)
print(df.duplicated().sum())

0

In [37]:
# fill numerical values for numerical columns with mean
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df['Years of Experience']=df['Years of Experience'].fillna(df['Years of Experience'].mean())

#fill mode for object datatype
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
df['Job Title']=df['Job Title'].fillna(df['Job Title'].mode()[0])
df['Education Level']=df['Education Level'].fillna(df['Education Level'].mode()[0])

In [38]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [39]:
#Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Education Level']=le.fit_transform(df['Education Level'])

#1-hot encoding
df= pd.get_dummies(df,columns=['Job Title'],drop_first=True)

#mapping
mapping={'Male':1,'Female':0}
df['Gender']=df['Gender'].map(mapping)

In [40]:
#we have to change the float parameters
df['Age'] = df['Age'].astype(int)
df['Salary'] = df['Salary'].astype(int)
df['Years of Experience'] = df['Years of Experience'].astype(int)

In [41]:
df.dtypes

Age                           int64
Gender                        int64
Education Level               int64
Years of Experience           int64
Salary                        int64
                              ...
Job Title_UX Designer          bool
Job Title_UX Researcher        bool
Job Title_VP of Finance        bool
Job Title_VP of Operations     bool
Job Title_Web Developer        bool
Length: 178, dtype: object

In [42]:
df =df.astype(int)
print(df.dtypes)

Age                           int64
Gender                        int64
Education Level               int64
Years of Experience           int64
Salary                        int64
                              ...
Job Title_UX Designer         int64
Job Title_UX Researcher       int64
Job Title_VP of Finance       int64
Job Title_VP of Operations    int64
Job Title_Web Developer       int64
Length: 178, dtype: object